// Pre-generated by Claude (claude-sonnet-4-6) from engine data via scripts/generate-briefs.mjs
// TODO(native-speaker): verify sn/nd translations before submission.
window.HOZI_BRIEFS={
 "Mazowe": {
  "en": {
   "bullets": [
    {
     "dept": "Meteorological Services Department",
     "action": "Issue a formal seasonal outlook update for Mazowe District covering March–September 2026, flagging the projected rainfall deficit of approximately 84.5mm below the staple-crop threshold of ~100mm/month. This should be shared with Agritex field officers by end of January 2026 to allow timely advisory dissemination to smallholder farmers before the March risk inflection at 35.8."
    },
    {
     "dept": "Agritex",
     "action": "Prioritise Mazowe for an emergency crop-advisory campaign beginning no later than February 2026, when risk is still at 0–1. With vegetation index at 0.27 against a healthy benchmark of 0.70 and input availability at 80.7/100, extension officers should redirect remaining input stocks toward drought-tolerant variety promotion and soil-moisture conservation techniques before the April risk level of 44.4 is reached."
    },
    {
     "dept": "ZINWA",
     "action": "Conduct a rapid assessment of Mazowe's existing irrigation infrastructure to identify whether the current 25.1% irrigation coverage can be expanded on available schemes before the June–July period when forecast risk rises to 55.8–72.7. Even modest coverage gains could reduce dependence on the 15.5mm/month rainfall, which is 84.5mm short of what staple crops require."
    },
    {
     "dept": "GMB (Grain Marketing Board)",
     "action": "Pre-position strategic grain reserves at Mazowe district depots ahead of the August–September window, when forecast risk reaches 80.0–84.9. Note that applying the full support package is modelled to reduce September risk by 9.5 points to 75.4; reserve quantities should therefore be sized for a residual high-risk scenario, not a resolved one."
    },
    {
     "dept": "Ministry of Public Service, Labour & Social Welfare",
     "action": "Flag Mazowe for early inclusion in the 2026 mid-year humanitarian caseload review, given that risk crosses the 50-point threshold in May 2026 and reaches 84.9 by September. With 12.5 pest incidents already recorded as a current driver, vulnerable households may face compounding shocks; social-protection targeting lists should be updated using ward-level Agritex data no later than April 2026."
    }
   ],
   "note": "The risk trajectory for Mazowe is steep and consistent — rising from 0 in February to 84.9 by September 2026 — making early pre-March action the highest-leverage window; however, the forecast cannot account for sudden beneficial rainfall events, localised pest outbreak escalation beyond the current 12.5 incidents, or changes in national grain import volumes that could materially alter household food access."
  },
  "sn": {
   "bullets": [
    {
     "dept": "Meteorological Services Department",
     "action": "Budiriro yekunaya kwemvura muDunhu reMazowe kubva Kurume kusvika Gunyana 2026 inofanira kuburitswa nekukurumidza, ichiratidzira kuti mvura iri kudonha zvinenge 84.5mm pazasi pechikero che~100mm pagore. Mashoko aya anofanira kusvika kuvadzidzisi veAgritex musati maMarch, panguva iyo njodzi ichakwira kuenda pa35.8."
    },
    {
     "dept": "Agritex",
     "action": "Vadzidzisi veminda vanofanira kutangira campaign yekupa mazano eminda muMazowe asati apfuura Kukadzi 2026, panguva iyo njodzi iri pakati pe0 ne1. Nekuti index yeminda iri pa0.27 (yakanaka inenge 0.70) uye zvigadzirwa zviri pa80.7/100, vadzidzisi vanofanira kukurudzira marudzi emhezi anokwanisa kutsungirira zuwa uye nzira dzekuchengetedza mvura mumvura musina mvura."
    },
    {
     "dept": "ZINWA",
     "action": "Kuongorora nekukurumidza zvishandiso zvemvura mune nzira dzekudiridza muMazowe, zvichida kuti chipikirwa che25.1% chekudiridza chinogona kuwedzerwa musati maMuvhuro–Chikunguru, panguva iyo njodzi ichisvika pa55.8–72.7. Kuwedzera kudiridza kunogona kubatsira kupa mvura imwe nzira ichangosiirwa pe15.5mm pagore."
    },
    {
     "dept": "GMB (Grain Marketing Board)",
     "action": "Kuchengetedza zviyo zvekuchengetedza muzvitoro zveMazowe musati maAugust–Gunyana, panguva iyo njodzi ichisvika pa80.0–84.9. Shandisa yese yerutsigiro inoratidzwa kuti inoderedza njodzi yaGunyana ne9.5 kuenda pa75.4; saka mhando yechiyo inofanira kusarudzwa yekurangarira mamiriro ari nechenjera, kwete yakaponeswa."
    },
    {
     "dept": "Ministry of Public Service, Labour & Social Welfare",
     "action": "Mazowe anofanira kuiswa pakati pevanhu vanoda rubatsiro rwe2026, nekuti njodzi inokwira pamusoro pe50 muna Chivabvu uye inosvika pa84.9 naGunyana. Nekuvepo kwe12.5 zvikurudziro zvematunhu ari kushandika, mhuri dzisina simba dzinogona kutambura; mareji ekubatsira anofanira kushandurwa uchishandisa data yeAgritex musati maNisani 2026."
    }
   ],
   "note": "Nzira yenjodzi muMazowe inokwira zvakaoma — ichibva pa0 muna Kukadzi ichisvika pa84.9 naGunyana 2026 — saka zviito zvakajeka musati maMarch ndizvo zvinobatsira zvakanyanya; asi forecast haigoni kuratidzira kunaya kwemvura kungangoitika, kuwedzera kwezvipembenene pamusoro pe12.5 zvikurudziro zvazvino, kana kuchinja kwemhando yegorosi inouya panze izvo zvinogona kushandura nzira yekuwana zvokudya mudzimba."
  },
  "nd": {
   "bullets": [
    {
     "dept": "Meteorological Services Department",
     "action": "Ukwethulwa kwemibiko yesizulu esithinta iSigodi seMazowe kusukela ngoMashi kuya kuSepthemba 2026 kufanele kwenziwe ngokushesha, kukhangelisa ukuthi izulu liyehlela ngapha kwama-84.5mm ngaphansi komgomo we~100mm ngenyanga. Lolu lwazi kufanele lufikele abasebenzi beAgritex bengakafiki uMashi, lapho ingozi izakhuphuka ifike ku-35.8."
    },
    {
     "dept": "Agritex",
     "action": "Izikhungo zeAgritex kufanele ziqalise umkhankaso wokweluleka abalimi eMazowe lingakafiki uFebruwari 2026, ngesikhathi ingozi isekuphakathi kuka-0 no-1. Nge-index yomhlaba engama-0.27 (ephilile ingema-0.70) kanye nezinto zokutshala ezingama-80.7/100, abasebenzi kufanele bakhuthaze izinhlobo zezilimo ezimelana nesomiso kanye nezindlela zokugcina umswakama womhlaba ngaphambi kuka-Epreli lapho ingozi ifikelela ku-44.4."
    },
    {
     "dept": "ZINWA",
     "action": "Ukuhlolwa ngokushesha kwezakhiwo zokuselela amanzi eMazowe kufanele kwenziwe ukuze kubonakale ukuthi isigaba esama-25.1% sokushelela amanzi singakhuliswa ngaphambi kweJulayi, lapho ingozi ebikezelwe ifikela ku-55.8–72.7. Noma ukwanda okuncane kokushelela amanzi kungasiza ukunciphisa ukuncika ezulwini elimanga ama-15.5mm ngenyanga."
    },
    {
     "dept": "GMB (Grain Marketing Board)",
     "action": "Ukubeka ukudla okubekiweyo ezitolo zeSigodi seMazowe ngaphambi kweNcwabakazi–uSepthemba, lapho ingozi ebikezelwe ifikela ku-80.0–84.9. Iphakheji yesekelo egcwele iboniswa ukunciphisa ingozi kaSepthemba nge-9.5 pойнта iye ku-75.4; ngakho izinga lezakho kufanele lihlelelwe isimo esisenengozi, hhayi esilungisiwe."
    },
    {
     "dept": "Ministry of Public Service, Labour & Social Welfare",
     "action": "IMazowe kufanele ifakwe ohlelweni lokubona abantu abadinga usizo ngo-2026, njengoba ingozi idlula amanani angama-50 ngoMeyi bese ifikelela ku-84.9 ngoSepthemba. Ngezikhungo ze-12.5 zezifo nezinambuzane ezisebenzayo njengamanje, imindeni esizungu ingabhekana nezinselelo ezihlanganisiwe; amarekhodi okusekela kufanele abuyekezwe kusetshenziswa idatha yeAgritex yezigodi lingakafiki uEpreli 2026."
    }
   ],
   "note": "Indlela yengozi eMazowe iyakhula ngamandla — isuka ku-0 ngoFebruwari ifikele ku-84.9 ngoSepthemba 2026 — ngakho izenzo zangaphambi kukaMashi yilapho usizo lungaba khona kakhulu; kodwa-ke, ukubikezela akukwazi ukubona imvula engaziwa engahle yeze, ukwanda kwezifo noma izinambuzane ngaphezu kwe-12.5 okukhona manje, noma ukushintsha kwezinga lokudla okungena ezweni okungathinta ukufinyelela kukudla kwemindeni."
  }
 },
 "Harare Urban": {
  "en": {
   "bullets": [
    {
     "dept": "Meteorological Services Department",
     "action": "Issue an updated seasonal outlook for Harare Urban for February–September 2026, specifically flagging the observed rainfall deficit of 12.9mm/month against the staple-crop requirement of approximately 100mm/month. Distribute this outlook to Agritex district officers and the Ministry of Lands & Agriculture no later than end-January 2026 to anchor all downstream planning decisions."
    },
    {
     "dept": "Agritex",
     "action": "Given the vegetation index of 0.17 against a healthy benchmark of 0.70, and 6 recorded pest incidents, deploy extension officers to conduct rapid field assessments across Harare Urban's peri-urban growing zones in February 2026. Assessments should document crop stand condition, pest species present, and remaining input stocks, feeding results directly into the Ministry of Lands & Agriculture's March planning cycle. Input availability is currently rated 83.8/100 and should be protected before the risk index crosses 55.3 in June."
    },
    {
     "dept": "ZINWA",
     "action": "With irrigation coverage at 41.6% and monthly rainfall at 12.9mm, ZINWA should audit current irrigation infrastructure capacity in Harare Urban by March 2026 and propose a prioritised schedule for extending or rehabilitating coverage to the most productive peri-urban plots. A 6.5-point risk reduction is available if the full support package is applied; irrigation reliability is a direct lever within ZINWA's mandate."
    },
    {
     "dept": "GMB (Grain Marketing Board)",
     "action": "Pre-position strategic grain reserves accessible to Harare Urban ahead of the June–September window, when the forecast risk index rises from 55.3 to 72.2. GMB should coordinate with the Ministry of Lands & Agriculture to confirm buffer-stock thresholds that reflect an urban district with limited own-production capacity, and ensure distribution points are mapped and operational before risk exceeds 60.0 in July 2026."
    },
    {
     "dept": "Ministry of Public Service, Labour & Social Welfare",
     "action": "With the September risk index forecast at 72.2 (reduced to 65.7 only if the full support package is applied), the Ministry should begin caseload reviews for existing urban social-protection beneficiaries in Harare by April 2026 and model a contingency expansion scenario for May–September. This is particularly important given the district's urban character, where market-dependent households are disproportionately exposed to food-price shocks driven by the escalating risk trajectory."
    }
   ],
   "note": "The risk trajectory rises steeply and continuously from 4.7 in January to 72.2 by September 2026, and the full support package reduces September risk by only 6.5 points, underscoring that early, coordinated action is urgent; however, this forecast cannot account for mid-season rainfall recovery, changes in national import volumes, or urban market price dynamics that may materially alter actual food-security outcomes."
  },
  "sn": {
   "bullets": [
    {
     "dept": "Meteorological Services Department",
     "action": "Budiriro yemamiriro ekunze yemwaka weMbudzi kunaGunyana 2026 inofanira kubuda nekukurumidza, ichiratidza kuti mvura iri kudonha 12.9mm pamwedzi chete, asi zvirimwa zvinoda anenge 100mm. Mashoko aya ngaapfuuidzwe kuAgritex neMusika weHurumende weZvirimwa (Ministry of Lands & Agriculture) kusati kwapera Ndira 2026."
    },
    {
     "dept": "Agritex",
     "action": "Vegetation index iri pa0.17, ichipesana ne0.70 inoratidzira utano hwakanaka, uye kune zvipembenene 6 zvakaonekwa. Agritex inofanira kutuma vashandi vayo kunoongorora minda yeperi-urban muHarare Urban muna Kukadzi 2026, vachizivisa Ministry yeZvirimwa nezve mamiriro ezvirimwa, zvirimwa zvakafa, uye zvinhu zvemunda zviripo. Zvinhu zvemunda zviripo zviri pa83.8/100 uye zvinofanira kurindirwa."
    },
    {
     "dept": "ZINWA",
     "action": "Nekuda kwekuti mvura iri shoma (12.9mm pamwedzi) uye irrigation coverage iri pa41.6%, ZINWA inofanira kuongorora zvigadzirwa zvayo zvekudiridza muHarare Urban muna Kurume 2026 uye ikurumidzise kukoreresa nokuvandudzira minda inoshanda kwazvo. Kudzikiswa kwerisk nemazana matanhatu nehafu kunogonekwa kana chirongwa chose chikashandiswa."
    },
    {
     "dept": "GMB (Grain Marketing Board)",
     "action": "GMB inofanira kuisa zviyo zvekuchengeta muHarare Urban kusati kwapinda nguva yaMbudzi kunaGunyana, apo risk index inofungidzirwa kukwira kubva pa55.3 kusvika pa72.2. Nzvimbo dzekugovera zviyo dzinofanira kugadzirwa uye kushanda zvirimwa risk isati yakwira pa60.0 muna Chikunguru 2026."
    },
    {
     "dept": "Ministry of Public Service, Labour & Social Welfare",
     "action": "Nekuti risk index yaSeptember inofungidzirwa kusvika pa72.2 (inoburuka kusvika pa65.7 chete kana chirongwa chose chakashandiswa), Musika uyu unofanira kutanga kuongorora vanhu vari muchirongwa chekubatsira muHarare kubva muna Kubvumbi 2026, uye ugadzirire chirongwa chekuwedzerwa kwemabetsero kwaMay kunaGunyana."
    }
   ],
   "note": "Nzira yerisk inokwira zvakakomba kubva pa4.7 muna Ndira kusvika pa72.2 muna Gunyana 2026, uye chirongwa chose chekubatsira chinoburitsa risk nemazana matanhatu nehafu chete muna Gunyana, saka kuita zvinhu nekukurumidza kwakakosha kwazvo; asi forecast iyi haigoni kuziva kana mvura ikawanda pakati pemwaka, kana mwero wezvirimwa zvinopinda munyika ukachinja, kana mitengo yemusika muHarare ukachinja zvinogona kushandura mamiriro echokwadi ekudya."
  },
  "nd": {
   "bullets": [
    {
     "dept": "Meteorological Services Department",
     "action": "Ihlelo lezulu lemozulu lesikhathi uJanuwari kuya kuSepthemba 2026 kufanele likhishwe masinyane, libonisa ukuthi izimvula ziwa ngo-12.9mm ngenyanga kuphela, kuyilapho izilimo zidinga cishe i-100mm. Lezi zalukazi kufanele zinikwe iAgritex leNyanga yeZikhungo zoMhlaba loLimu (Ministry of Lands & Agriculture) ngaphambi kokugcina kukaJanuwari 2026."
    },
    {
     "dept": "Agritex",
     "action": "I-vegetation index ingama-0.17 kuphikisana lombono ophilileyo wama-0.70, futhi kukhona izinhlungu eziyisithupha ezirekhodiwe. IAgritex kufanele ithumele izisebenzi zayo ukuyophenyisisa amasimu ase-peri-urban eHarare Urban ngoFebruwari 2026, zibike ngemimo yezilimo, izinambuzane, lezinto zezimu ezikhona. Izinto zezimu zikhona ngama-83.8/100 futhi kufanele zilondolozwe."
    },
    {
     "dept": "ZINWA",
     "action": "Njengoba izimvula zingama-12.9mm ngenyanga lokusibekela kwezinhlelo zokuthela amanzi kuyingxenye yama-41.6%, iZINWA kufanele ihlole amandla ezingqalasizinda zokuthela amanzi eHarare Urban ngoMashi 2026 futhi iphakamise uhlelo lokwandiswa nokulingana kwazo ezindaweni ezivelisa kakhulu. Ukwehla kwerisk nge-6.5 kunenzuzo uma isifundo sonke sakusekela sisetshenziswa."
    },
    {
     "dept": "GMB (Grain Marketing Board)",
     "action": "I-GMB kufanele ibeke izikhungo zokudla ezisemthethweni eHarare Urban ngaphambi kwesikhathi sikaJuni kuya kuSepthemba, lapho i-risk index ibonakala ikhula kusuka kuma-55.3 kuya kuma-72.2. Izindawo zokusabalalisa ukudla kufanele zilungiswe futhi zisebenze ngaphambi kokuba i-risk yeqe i-60.0 ngoJulayi 2026."
    },
    {
     "dept": "Ministry of Public Service, Labour & Social Welfare",
     "action": "Njengoba i-risk index kaSepthemba ibonakala ifinyelela kuma-72.2 (yehliswa kufinyelela kuma-65.7 kuphela uma isifundo sonke sisetshenzisiwe), iNyanga kufanele iqale ukubuyekeza uhlu lwabantu abaphethwe yizinhlelo zokusekela eHarare ngo-Ephreli 2026, futhi ilungiselele uhlelo lokukhuliswa ezikhathini zaseMeyi kuya kuSepthemba."
    }
   ],
   "note": "Umkhondo we-risk ukhula kakhulu njalo kusuka kuma-4.7 ngoJanuwari uya kuma-72.2 ngoSepthemba 2026, futhi isifundo sonke sokusekela sehla i-risk ngo-6.5 kuphela ngoSepthemba, okusho ukuthi ukwenza izinto masinyane kubalulekile kakhulu; kodwa-ke, le-forecast ayikwazi ukwazi ukuthi izimvula zingabuya phakathi kwesizini, noma izinga lokufakwa kokudla ezweni lingashintsha, noma imiphakathi yezinto eHarare ingashintsha ngendlela engashintsha imiphumela yangempela yokuphepha kokudla."
  }
 },
 "Chitungwiza": {
  "en": {
   "bullets": [
    {
     "dept": "Meteorological Services Department",
     "action": "Issue a formal sub-seasonal outlook for Chitungwiza covering February–September 2026, with explicit reference to the recorded 21.1 mm/month rainfall deficit against the ~100 mm/month staple-crop requirement. Distribute findings directly to Agritex district officers to inform planting and supplemental-irrigation advisories before the April risk threshold of 35.5 is reached."
    },
    {
     "dept": "Agritex",
     "action": "Deploy extension officers to assess the 5 recorded pest incidents at field level and initiate a rapid integrated pest management response. Given the vegetation index of 0.26 against a healthy benchmark of ~0.70, prioritise crop-condition surveys in the most stressed smallholder plots and report findings to the Ministry of Lands & Agriculture no later than end of March 2026, before the May risk score of 53.0 is projected."
    },
    {
     "dept": "ZINWA",
     "action": "Audit existing irrigation infrastructure in Chitungwiza to identify the operational gap within the 47.7% irrigation coverage figure. Develop a prioritised rehabilitation schedule targeting the highest-yield smallholder blocks, with the aim of incrementally reducing the rainfall-deficit exposure as scores escalate from 53.0 in May toward 71.7 in September 2026."
    },
    {
     "dept": "GMB (Grain Marketing Board)",
     "action": "Given the input availability index of 71.6 out of 100 and the risk trajectory reaching 67.9 by August 2026, pre-position certified seed and fertiliser stocks for Chitungwiza ahead of any further supply deterioration. Coordinate with the Ministry of Lands & Agriculture to align stock levels with Agritex-identified at-risk household counts from field surveys."
    },
    {
     "dept": "Ministry of Public Service, Labour & Social Welfare",
     "action": "Initiate a household vulnerability screening in Chitungwiza now, using the current risk score of 35.5 (April) as the trigger threshold, to prepare a verified beneficiary list for the social-protection support package. Modelling indicates that timely application of this package can reduce the September risk score from 71.7 to 65.4 — a 6.3-point reduction — but activation lead time must be factored into planning immediately."
    }
   ],
   "note": "The risk trajectory for Chitungwiza is on a sustained upward path from April onward, reaching an estimated 71.7 by September 2026, and warrants coordinated early action now; however, this forecast cannot account for sudden mid-season policy changes, emergency humanitarian inflows, or rainfall events that diverge materially from the current 21.1 mm/month baseline."
  },
  "sn": {
   "bullets": [
    {
     "dept": "Meteorological Services Department",
     "action": "Buritsa chirevo che sub-seasonal chemvura yeChitungwiza chinosanganisira Kukadzi kusvika Gunyana 2026, uchitsanangura pachena kuti mvura iri kusvika 21.1 mm pane ~100 mm inodikanwa pazvirimwa. Tuma zvigumisiro kumaofisi eAgritex edunhu kuti vashandise mumazano ekudyara uye kushandisa mvura yekudiridza mvura yatangira kuderera kwanguva yeApril ine score ye 35.5."
    },
    {
     "dept": "Agritex",
     "action": "Tumira maofisa ekutarisira kurima kunoongorora matambudziko mashanu ezvipembenene akanyorwa uye vatange kudzivisa zvipembenene izvi. Nekuda kwe vegetation index ye 0.26 pane yakakwana ye ~0.70, tanga nokukurumidza kuongorora minda yevashandi vadiki uye utuma mushumo kuMusha weHurumende yeNyika neMinda Kusati kwapera Kurume 2026."
    },
    {
     "dept": "ZINWA",
     "action": "Ongorora zvigadzirwa zvekudiridza muna Chitungwiza kuti uzive kuti nei chete 47.7% yeminda inodiridza. Gadzira chirongwa chekugadziriswa kwebasa zvichienderana nematamba ane nzara kureba, uchicherecheda kuti score inokwira kubva 53.0 muna Chivabvu kusvika 71.7 muna Gunyana 2026."
    },
    {
     "dept": "GMB (Grain Marketing Board)",
     "action": "Nekuda kwekuti zvinhu zvekurima zviripo pa 71.6 pane 100 uye nhamba yerisk ichisvika 67.9 muna Nyamavhuvhu 2026, gadzirira mbeu dzakachekwa uye mbofu yekunoisa muna Chitungwiza usati wamirira kuderera kwezvinhu. Budiridzana neMusha weHurumende yeNyika neMinda kuti zvinhu zvakwane nezvakawanwa naAgritex pahurumende dzinoshayiwa."
    },
    {
     "dept": "Ministry of Public Service, Labour & Social Welfare",
     "action": "Tanga kuongorora mamisha ari mudunhu reChitungwiza iye zvino, uchishandisa score ye 35.5 yeApril semuyedzo wekutanga, kuti ugadzire rondedzero yevakagadziridzwa kuchengetedza. Chirongwa chekubatsira chinogona kudzika score yeGunyana kubva 71.7 kusvika 65.4 — kubvarura kwe 6.3 — asi chirongwa chinofanira kutangwa nekukurumidza."
    }
   ],
   "note": "Nhamba yerisk yeChitungwiza inokwira zvakasimba kubva Kubvumbi kuenda mberi, ichisvika 71.7 muna Gunyana 2026, uye inoda zviito zvekutanga zvakarongeka iye zvino; asi chirongwa ichi hachigoni kuziva shanduko dzehurumende, rubatsiro rwekukurumidza, kana mvura inogona kuuya zvisingatarisirwi."
  },
  "nd": {
   "bullets": [
    {
     "dept": "Meteorological Services Department",
     "action": "Khipha isaziso se-sub-seasonal semvula eChitungwiza esihlanganisa uNhlolanja kuze kube nguNcwabakazi 2026, uchichaza ngokusobala ukuthi imvula efikayo nge-21.1 mm iyaswela kakhulu uma iqathaniswa ne-~100 mm edingekayo ekulimeni. Thumela imiphumela kumaofisi e-Agritex esifundeni ukuze basebenzise izeluleko zokulima nokuchwayisa izitshalo ngaphambi kokuba isilinganiso sika-Ephireli sifikele ku-35.5."
    },
    {
     "dept": "Agritex",
     "action": "Thumela iziphathimandla zekulima ukuze zihlole izigameko ezinhlanu ezibhaliwe zamagciwane ezitshalweni, bese baqala ukuvimba. Ngoba i-vegetation index ingama-0.26 uma iqathaniswa ne-~0.70 ephilile, qala kabusha ukubheka izinsimu zabalimi abancane abahluphekayo futhi uthumele imibiko kuMnyango Wezemihlaba Nezolimo ngaphambi kwekupheleni kukaMashi 2026."
    },
    {
     "dept": "ZINWA",
     "action": "Hlola ingqalasizinda yokuhlomisa amanzi eChitungwiza ukuze uzwisise ukuthi kungani kuphela u-47.7% wamazwe ahlomiswa amanzi. Yenza uhlelo lokuphucuzwa oluqondiswe ezindaweni zabalimi abancane ezikhiqiza kakhulu, ucabangele ukuthi isilinganiso sonyaka sisuka ku-53.0 ngoNhlaba siye ku-71.7 nguNcwabakazi 2026."
    },
    {
     "dept": "GMB (Grain Marketing Board)",
     "action": "Njengoba i-indeksi yokutholakala kwezinketho ingama-71.6 kwewu-100 futhi isilinganiso sengozi sifikele ku-67.9 ngoNcwaba 2026, lungisa imbewu eqinisekisiwe kanye namazotho okusebenza eChitungwiza ngaphambi kokuba izinto ziwohloke kakhulu. Xhumana noMnyango Wezemihlaba Nezolimo ukuze izinga lentengo lihambelane nezinombolo zabasebenzi abahluphekayo ezitholwe yi-Agritex."
    },
    {
     "dept": "Ministry of Public Service, Labour & Social Welfare",
     "action": "Qala ukuhlola imindeni eChitungwiza manje, usebenzisa isilinganiso sika-Ephireli esingu-35.5 njengekheli lokuqala, ukuze ulungiselele uhlu lwabantu abazosizwa wuhlelo lokuvikelwa. Ukumodela kubonisa ukuthi ukusebenzisa ngesikhathi kwaleli package kungehla isilinganiso sikaNcwabakazi kusuka ku-71.7 kuye ku-65.4 — ukwehla kwe-6.3 — kodwa isikhathi sokulungiselela kumele sibandakanywe ekulaveni manje."
    }
   ],
   "note": "Isilinganiso sengozi seChitungwiza senyuka ngokuqhubekayo kusukela ngo-Ephireli, sifikele ku-71.7 ngo-Ncwabakazi 2026, futhi sidinga izenzo zokuqala ezihlanganiswayo manje; nokho, lesi sibikezelo asinakwazi ukuziba izinguquko ezingalindelekile zenqubomgomo, ukufika kwezinsiza zocwaningo, noma izehlo zemvula ezingahluka kakhulu kuya kolwazi lwamanje lwe-21.1 mm ngenyanga."
  }
 }
};
