// Pre-generates per-district intervention playbooks with Claude.
// Usage:  node scripts/generate-briefs.mjs            (all 20 districts)
//         node scripts/generate-briefs.mjs Mazowe     (one district, for testing)
// Requires: scripts/anthropic-key.txt (git-ignored) containing only the API key.
// Output:  app/briefs.js  ->  window.HOZI_BRIEFS = { "<district>": {en:{...},sn:{...},nd:{...}} }
import { readFileSync, writeFileSync, existsSync } from "fs";

const KEY_FILE = "scripts/anthropic-key.txt";
if (!existsSync(KEY_FILE)) { console.error(`Missing ${KEY_FILE} — create it with only your Anthropic API key inside.`); process.exit(1); }
const API_KEY = readFileSync(KEY_FILE, "utf8").trim();
const MODEL = "claude-sonnet-4-6";

const load = (p) => { const window = {}; eval(readFileSync(p, "utf8")); return window; };
const HOZI = load("app/projections.js").HOZI;
const only = process.argv[2];
const districts = HOZI.districts.filter(d => !only || d.district === only);

const SYSTEM = `You are Hozi, Zimbabwe's food-security foresight engine, drafting early-action
intervention briefs for government planners. Rules:
- Ground EVERY statement in the numbers provided. Never invent figures, places, or programmes.
- Map each action to a real Zimbabwean institution: Agritex, Ministry of Lands & Agriculture,
  DDF (District Development Fund), GMB (Grain Marketing Board), Ministry of Public Service,
  Labour & Social Welfare, ZINWA, Meteorological Services Department, Rural District Council.
- Tone: calm, specific, advisory. These are recommendations for human review — never orders.
- The engine runs on POTRAZ synthetic challenge data; briefs are illustrative of the production system.
Respond with ONLY valid JSON, no markdown fences, in this exact shape:
{"en":{"bullets":[{"dept":"...","action":"..."}],"note":"..."},
 "sn":{"bullets":[{"dept":"...","action":"..."}],"note":"..."},
 "nd":{"bullets":[{"dept":"...","action":"..."}],"note":"..."}}
- 3 to 5 bullets per language. "sn" = chiShona, "nd" = isiNdebele (translate the same content naturally).
- "note" = one honest sentence on urgency and what the forecast cannot know.`;

function districtPrompt(d) {
  const tl = d.timeline.map(x => `${x.m}: ${x.risk}${x.proj ? " (forecast)" : ""}`).join(", ");
  const dr = d.latest_drivers || {};
  return `District: ${d.district} (${d.province} province)
Risk timeline 0-100 (Jan-Sep 2026): ${tl}
Latest drivers: rainfall ${dr.rainfall_mm}mm/month (staples need ~100mm), vegetation index ${dr.ndvi} (healthy ~0.70), pest incidents ${dr.pest}, irrigation coverage ${dr.irrigation}%, input availability ${dr.inputs}/100.
Support-package effect if applied: September risk falls by ${d.support?.reduction ?? "n/a"} points to ${d.support?.supported_sep ?? "n/a"}.
Write the intervention brief.`;
}

async function callClaude(prompt) {
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: { "x-api-key": API_KEY, "anthropic-version": "2023-06-01", "content-type": "application/json" },
    body: JSON.stringify({ model: MODEL, max_tokens: 4000, system: SYSTEM,
      messages: [{ role: "user", content: prompt }] })
  });
  if (!res.ok) throw new Error(`API ${res.status}: ${await res.text()}`);
  const data = await res.json();
  return data.content[0].text.trim();
}

const out = existsSync("app/briefs.js")
  ? load("app/briefs.js").HOZI_BRIEFS || {}
  : {};

let usage = 0;
for (const d of districts) {
  if (out[d.district] && !only) { console.log(`${d.district} ... already done, skipping`); continue; }
  process.stdout.write(`${d.district} ... `);
  try {
    let text = await callClaude(districtPrompt(d));
    text = text.replace(/^```(json)?/,'').replace(/```$/,'').trim();
    out[d.district] = JSON.parse(text);
    console.log("ok");
  } catch (e) { console.log("FAILED:", e.message); }
}

writeFileSync("app/briefs.js",
  "// Pre-generated by Claude (" + MODEL + ") from engine data via scripts/generate-briefs.mjs\n" +
  "// TODO(native-speaker): verify sn/nd translations before submission.\n" +
  "window.HOZI_BRIEFS=" + JSON.stringify(out, null, 1) + ";\n");
console.log(`\nWrote app/briefs.js with ${Object.keys(out).length} district briefs.`);
